#!/usr/bin/bash

python training_under_exploring.py ../../data_coded/anuran_defense/esm1b/training_dataset.csv ../../data_coded/anuran_defense/esm1b/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/esm1b/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_0/training_dataset.csv ../../data_coded/anuran_defense/Group_0/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_0/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_0_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_0_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_0_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_1/training_dataset.csv ../../data_coded/anuran_defense/Group_1/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_1/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_1_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_1_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_1_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_2/training_dataset.csv ../../data_coded/anuran_defense/Group_2/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_2/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_2_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_2_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_2_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_3/training_dataset.csv ../../data_coded/anuran_defense/Group_3/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_3/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_3_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_3_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_3_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_4/training_dataset.csv ../../data_coded/anuran_defense/Group_4/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_4/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_4_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_4_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_4_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_5/training_dataset.csv ../../data_coded/anuran_defense/Group_5/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_5/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_5_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_5_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_5_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_6/training_dataset.csv ../../data_coded/anuran_defense/Group_6/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_6/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_6_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_6_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_6_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_7/training_dataset.csv ../../data_coded/anuran_defense/Group_7/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_7/
python training_under_exploring.py ../../data_coded/anuran_defense/Group_7_FFT/training_dataset.csv ../../data_coded/anuran_defense/Group_7_FFT/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/Group_7_FFT/
python training_under_exploring.py ../../data_coded/anuran_defense/one_hot/training_dataset.csv ../../data_coded/anuran_defense/one_hot/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/one_hot/
python training_under_exploring.py ../../data_coded/anuran_defense/prottrans_albert/training_dataset.csv ../../data_coded/anuran_defense/prottrans_albert/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/prottrans_albert/
python training_under_exploring.py ../../data_coded/anuran_defense/prottrans_bert/training_dataset.csv ../../data_coded/anuran_defense/prottrans_bert/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/prottrans_bert/
python training_under_exploring.py ../../data_coded/anuran_defense/prottrans_t5bdf/training_dataset.csv ../../data_coded/anuran_defense/prottrans_t5bdf/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/prottrans_t5bdf/
python training_under_exploring.py ../../data_coded/anuran_defense/prottrans_uniref/training_dataset.csv ../../data_coded/anuran_defense/prottrans_uniref/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/prottrans_uniref/
python training_under_exploring.py ../../data_coded/anuran_defense/prottrans_xlnet/training_dataset.csv ../../data_coded/anuran_defense/prottrans_xlnet/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/prottrans_xlnet/
python training_under_exploring.py ../../data_coded/anuran_defense/prottrans_xlu50/training_dataset.csv ../../data_coded/anuran_defense/prottrans_xlu50/validation_dataset.csv 30 ../../results_explored_by_task/anuran_defense/prottrans_xlu50/
